import Head from "next/head";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { getComics } from "dh-marvel/services/marvel/marvel.service";
import { Comic } from "shared/types/apiSchema";
import { Box, Button, CardMedia, Grid, Link, Typography } from "@mui/material";

export async function getStaticProps(){
  const data = await getComics(0,12)
  return {
    props: {data}
  }
}

type IndexPageProps = {
  data: {
    data: {
      results: Comic[]
    }
  }
}

const handleOnClick = async() =>{
  const offSet = await getComics()
}

const Index = (props: IndexPageProps) => {
  const {data} = props
  const issues = data.data.results
  return (
    <>
      <Head>
        <title>CheckPoint Final</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BodySingle title={"Marvel HQ"}>
          <Box sx={{margin: '0 20px', flexFGrow: 1}}>
      <Grid sx={{ justifyContent: 'center' }} container spacing={2}>
            {issues.map((issue: Comic) => (
              <Grid key={issue.id} width={350} item>
                <Typography
                align='center'
                gutterBottom
                noWrap
                variant="h6"
                component="div"
                >
                {issue.title}  
                </Typography>
                <CardMedia
                component='img'
                height='140'
                image={`${issue.thumbnail.path}.${issue.thumbnail.extension}`}
                alt={issue.title}/>
                <div style={{ display: 'flex', justifyContent: 'center', gap: 10, marginTop: 10 }}>
                <Link href={`/checkout/${issue.id}`}>
                  <Button color='secondary' variant="contained">Comprar</Button>
                </Link>
                <Link href={`/issue/${issue.id}`}>
                  <Button>
                    Detalhes
                  </Button>
                </Link>
                <Button onClick={handleOnClick}></Button>
              </div>
              </Grid>
            ))}
          </Grid>
          </Box>
      </BodySingle>
    </>
  );
};

export default Index;
